apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/HumanValley/sajansse_inceptionp3_app.git
    targetRevision: HEAD
    path: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
