apiVersion: v1
kind: Service
metadata:
  name: app-service         # Nom DNS : app1-service.default.svc.cluster.local
spec:
  selector:
    app: app                # Sélectionne tous les pods avec le label "app: app1"
  ports:
  - port: 80                # Port du Service (ce qu'on appelle de l'extérieur)
    targetPort: 80          # Port du container (nginx écoute sur 80)
