apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service         # Nom DNS : wil-playground-service.default.svc.cluster.local
spec:
  selector:
    app: wil-playground     # Sélectionne tous les pods avec le label "app: wil-playground"
  type: NodePort            # Permet d'ouvrir le port
  ports:
  - port: 80                # Port du Service (ce qu'on appelle de l'extérieur)
    targetPort: 80          # Port du container (nginx écoute sur 80)
    nodePort: 30080       # <-- port exposé sur le noeud (doit être entre 30000 et 32767)
